# Generated by Django 5.0.2 on 2024-03-11 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='instructor',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
