# Generated by Django 5.0.2 on 2024-03-11 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhysicalClassUser',
        ),
    ]
