# Generated by Django 5.0.2 on 2024-03-12 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_delete_physicalclassuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
