# Generated by Django 5.0.2 on 2024-03-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('total_amount', models.CharField(max_length=100)),
                ('transaction_code', models.CharField(max_length=500)),
                ('courseid', models.CharField(max_length=100)),
                ('transaction_uuid', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=500)),
            ],
        ),
    ]
